// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB97K08TUHqwQAbOESOC8gPqpqyDM5LLPc',
    appId: '1:228195658327:web:ff0c13baf74b6b58d85112',
    messagingSenderId: '228195658327',
    projectId: 'onespaceapp-1fe8b',
    authDomain: 'onespaceapp-1fe8b.firebaseapp.com',
    storageBucket: 'onespaceapp-1fe8b.firebasestorage.app',
    measurementId: 'G-BSQ5YW2E10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoQ-zbzUrmFFoSxa27Xmw-znSNfHPu3T8',
    appId: '1:228195658327:android:6db90a08ec263f20d85112',
    messagingSenderId: '228195658327',
    projectId: 'onespaceapp-1fe8b',
    storageBucket: 'onespaceapp-1fe8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_XPzcJePSUm07EPkXNCug-rb1_308AtI',
    appId: '1:228195658327:ios:77640931f81202afd85112',
    messagingSenderId: '228195658327',
    projectId: 'onespaceapp-1fe8b',
    storageBucket: 'onespaceapp-1fe8b.firebasestorage.app',
    iosBundleId: 'com.example.onespaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_XPzcJePSUm07EPkXNCug-rb1_308AtI',
    appId: '1:228195658327:ios:77640931f81202afd85112',
    messagingSenderId: '228195658327',
    projectId: 'onespaceapp-1fe8b',
    storageBucket: 'onespaceapp-1fe8b.firebasestorage.app',
    iosBundleId: 'com.example.onespaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB97K08TUHqwQAbOESOC8gPqpqyDM5LLPc',
    appId: '1:228195658327:web:bab04a9da7d44345d85112',
    messagingSenderId: '228195658327',
    projectId: 'onespaceapp-1fe8b',
    authDomain: 'onespaceapp-1fe8b.firebaseapp.com',
    storageBucket: 'onespaceapp-1fe8b.firebasestorage.app',
    measurementId: 'G-QRN5DBE776',
  );
}
