import 'package:flutter/material.dart';

class SimpleLocalizations {
  final Locale locale;

  SimpleLocalizations(this.locale);

  static final Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      'save_pin': 'Save PIN',
      'select_language': 'Select Language',
      'pin_set': 'PIN is set',
      'pin_not_set': 'No PIN set',
      'new_pin': 'New PIN',
      'confirm_pin': 'Confirm PIN',
      'overwrite_pin_title': 'Overwrite existing PIN?',
      'overwrite_pin_content': 'This will replace your current PIN. Continue?',
      'cancel': 'Cancel',
      'ok': 'OK',
      'add_profile': 'Add Profile',
      'staff_profiles': 'Staff Profiles',
      'child_profiles': 'Child Profiles',
      'age': 'Age',
      'delete': 'Delete',
      'access_denied': 'Access denied: incorrect PIN',
      'zones_regulation': 'Zones of Regulation',
      'points_overview': 'Points Overview',
      'view_schedule': 'View Schedule',
      'create_quiz': 'Create Quiz',
      'manage_quizzes': 'Manage Quizzes',
      'welcome': 'Welcome',
      'my_points': 'My Points',
      'my_schedule': 'My Schedule',
      'calming_sounds': 'Calming Sounds',
      'take_quiz': 'Take a Quiz',
      'change_background': 'Change Background Color',
      'voice_lines': 'Voice Lines',
      'voice_lines_title': 'Voice Lines',
      'visual_timer': 'Visual Timer',
      'start': 'Start',
      'pause': 'Pause',
      'reset': 'Reset',
      'time_finished': 'Time Finished',
      'min': 'min',
      'first_then': 'First Then',
      'first_then_setup': 'First Then Setup',
      'choose_who_this_applies_to': 'Choose who this applies to',
      'single': 'Single',
      'multiple': 'Multiple',
      'all': 'All',
      'select_child': 'Select Child',
      'select_children': 'Select Children',
      'applies_to_all_children': 'This will apply to all child profiles.',
      'select_activity': 'Select Activity',
      'select_three_reward_options': 'Select 3 Reward Options',
      'selected': 'Selected',
      'apply_first_then': 'Apply First Then',
      'first_then_applied': 'First Then applied successfully',
      'failed_to_apply_first_then': 'Failed to apply First Then',
      'select_activity_first': 'Please select an activity first',
      'select_three_rewards': 'Please select exactly 3 rewards',
      'select_child_first': 'Please select a child first',
      'select_at_least_one_child': 'Please select at least one child',
      'no_child_profiles_found': 'No child profiles found',
      'first': 'FIRST',
      'then': 'THEN',
      'then_choose_reward': 'THEN: Choose your reward',
      'no_active_first_then': 'No active First Then board right now',
      'quiz': 'Quiz',
      'homework': 'Homework',
      'clean_up': 'Clean Up',
      'finish_work': 'Finish Work',
      'playtime': 'Playtime',
      'outside_time': 'Outside Time',
      'break': 'Break',
      'music': 'Music',
    },
    'ga': {
      'save_pin': 'Sábháil PIN',
      'select_language': 'Roghnaigh Teanga',
      'pin_set': 'Tá PIN socraithe',
      'pin_not_set': 'Níl PIN socraithe',
      'new_pin': 'PIN Nua',
      'confirm_pin': 'Deimhnigh PIN',
      'overwrite_pin_title': 'An scríobhfaidh tú thar an PIN atá ann?',
      'overwrite_pin_content': 'Athróidh sé seo do PIN reatha. Lean ar aghaidh?',
      'cancel': 'Cealaigh',
      'ok': 'OK',
      'add_profile': 'Cuir Próifíl leis',
      'staff_profiles': 'Próifílí Foirne',
      'child_profiles': 'Próifílí Páistí',
      'age': 'Aois',
      'delete': 'Scrios',
      'access_denied': 'Rochtain diúltaithe: PIN mícheart',
      'zones_regulation': 'Zóin Rialaithe',
      'points_overview': 'Forbhreathnú Pointí',
      'view_schedule': 'Féach ar an Sceideal',
      'create_quiz': 'Cruthaigh Tástáil',
      'manage_quizzes': 'Bainistigh Tástálacha',
      'welcome': 'Fáilte',
      'my_points': 'Mo Phointí',
      'my_schedule': 'Mo Sceideal',
      'calming_sounds': 'Fuaimeanna Ciúine',
      'take_quiz': 'Glac Tráth na gCeist',
      'change_background': 'Athraigh Dath an Chúlra',
      'voice_lines': 'Línte Gutha',
      'voice_lines_title': 'Línte Gutha',
      'visual_timer': 'Amharcthaiméir',
      'start': 'Tosaigh',
      'pause': 'Sos',
      'reset': 'Athshocraigh',
      'time_finished': 'Tá an t-am críochnaithe',
      'min': 'nóim',
      'first_then': 'Ar dtús Ansin',
      'first_then_setup': 'Socrú Ar dtús Ansin',
      'choose_who_this_applies_to': 'Roghnaigh cé dó a bhaineann sé seo',
      'single': 'Aonair',
      'multiple': 'Iolrach',
      'all': 'Uile',
      'select_child': 'Roghnaigh páiste',
      'select_children': 'Roghnaigh páistí',
      'applies_to_all_children': 'Cuirfear seo i bhfeidhm ar gach próifíl páiste.',
      'select_activity': 'Roghnaigh gníomhaíocht',
      'select_three_reward_options': 'Roghnaigh 3 rogha luaíochta',
      'selected': 'Roghnaithe',
      'apply_first_then': 'Cuir Ar dtús Ansin i bhfeidhm',
      'first_then_applied': 'Cuireadh Ar dtús Ansin i bhfeidhm',
      'failed_to_apply_first_then': 'Theip ar Ar dtús Ansin a chur i bhfeidhm',
      'select_activity_first': 'Roghnaigh gníomhaíocht ar dtús',
      'select_three_rewards': 'Roghnaigh 3 luaíocht go díreach',
      'select_child_first': 'Roghnaigh páiste ar dtús',
      'select_at_least_one_child': 'Roghnaigh páiste amháin ar a laghad',
      'no_child_profiles_found': 'Níor aimsíodh próifílí páistí',
      'first': 'AR DTÚS',
      'then': 'ANSIN',
      'then_choose_reward': 'ANSIN: Roghnaigh do luaíocht',
      'no_active_first_then': 'Níl aon chlár Ar dtús Ansin gníomhach faoi láthair',
      'quiz': 'Tráth na gCeist',
      'homework': 'Obair Bhaile',
      'clean_up': 'Glan Suas',
      'finish_work': 'Críochnaigh an Obair',
      'playtime': 'Am Súgartha',
      'outside_time': 'Am Amuigh',
      'break': 'Sos',
      'music': 'Ceol',
    },
  };

  String getString(String key) {
    return _localizedStrings[locale.languageCode]?[key] ??
        _localizedStrings['en']![key] ??
        key;
  }
}